export const surpriseMePrompts = [
	"Un fauteuil en forme d'avocat",
	"Une peinture à l'huile surréaliste et onirique de Salvador Dalí représentant un chat jouant aux échecs",
	'Des ours en peluche faisant les courses pour des courses au Japon, en style ukiyo-e',
	"Une peinture à l'huile de Matisse représentant un robot humanoïde jouant aux échecs",
	'Un pandas scientifique fou mélangeant des produits chimiques pétillants, en art numérique',
	'Une photographie macro 35mm de deux souris à Hawaï, chacune portant un minuscule maillot de bain et tenant une petite planche de surf, en art numérique',
	"Un rendu 3D d'un poisson tropical mignon dans un aquarium sur un fond bleu foncé, en art numérique",
	"Un astronaut se reposant dans un resort tropical dans l'espace, en style vaporwave",
	"Un portrait à l'huile d'un capybara portant des robes royales médiévales et une couronne ornée sur un fond sombre",
	'Une fenêtre en vitrail représentant un hamburger et des frites',
	"un dessin à la mine de plomb et à l'aquarelle d'une ville lumineuse dans le futur avec des voitures volantes",
	"une zone de salon intérieur ensoleillée avec une piscine à eau claire et une autre piscine à eau pastel rose translucide, à côté d'une grande fenêtre, art numérique",
	"un shiba inu prédisant l'avenir en lisant votre destin dans un gros hamburger, art numérique",
	"un loutre de mer avec une boucle d'oreille en perle de Johannes Vermeer",
	"un dessin à l'huile de pastel d'un chat en colère dans une navette spatiale",
	"une peinture d'un renard dans le style de Nuit étoilée",
	'un bol de soupe qui ressemble à un monstre, tricoté en laine',
	'Un jouet en peluche robot assis contre un mur jaune',
	"un coucher de soleil de style synthwave au-dessus de l'eau reflétant de la mer, art numérique",
	'deux tours futuristes avec un pont ciel couvert de végétation luxuriante, art numérique',
	"une image de synthèse d'un ballon à air chaud arc-en-ciel volant au-dessus d'un lac réfléchissant",
	"une couverture de bande dessinée d'un super-héros portant des écouteurs",
	'une explosion colorée de poudre au centre sur un fond noir',
	"une photo d'un chien Samoyède avec sa langue dehors en train de serrer un chat Siamois blanc",
	"une photo d'un monstre en fourrure blanche debout dans une pièce violette",
	'une photo de la sculpture de David de Michel-Ange portant des écouteurs DJ',
	'Un samouraï chevauchant un cheval sur Mars, lomographie.',
	"Une Cadillac moderne et élégante qui roule sur l'autoroute Gardiner avec le centre-ville de Toronto en arrière-plan, avec un flare de lentille, photographie 50 mm",
	"une photographie réaliste d'une jeune femme aux yeux bleus et aux cheveux blond",
	'un homme debout devant un stargate vers une autre dimension',
	'SpongeBob SquarePants dans le projet Blair Witch',
	'un velociraptor travaillant à un stand de hot-dogs, lomographie',
	'un homme marchant dans les rues animées de Kowloon la nuit, éclairé par de nombreux panneaux lumineux de magasins néon, lentille 50 mm',
	"un BBQ qui est vivant, dans le style d'un film d'animation Pixar",
	'un club de danse cyborg futuriste, lumières néon',
	"L'anime Star Wars perdu des années 1990 au Japon",
	"Un hamburger en forme de Rubik's Cube, photographie professionnelle de nourriture",
	'Un hérisson synthwave, cyberpunk de Blade Runner',
	'Un astronaute rencontrant une forme de vie extraterrestre sur une planète lointaine, photographie',
	'Un dinosaure explorant le Cap, photographie',
	'Un homme tombant amoureux de son ordinateur, art numérique',
	"Une photographie d'un cyborg explorant Tokyo la nuit, lomographie",
	'Dracula marchant dans les rues de New York City dans les années 1920, photographie en noir et blanc',
	'Avion synthwave',
	'Un homme se promenant dans les rues pluvieuses de Tokyo, avec des panneaux lumineux néon, 50mm',
	'Un vaisseau spatial volant au-dessus du Cap, art numérique',
];
